[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm run install:all"]

[phases.build]
cmds = ["npm run build", "cd backend && npx prisma generate"]

[start]
cmd = "cd backend && npm start"
